👋 Bye bye, RxJava! 🚀
Simprints/Android-Simprints-ID pull request #1035
Opened 2024-12-30 04:04 UTC by meladRaouf

2024-12-31 15:20 UTC, alexandr-simprints requested changes
Please review the comments and verify that the code is correct

2025-01-06 08:24 UTC, luhmirin-s commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/cypressota/CypressOtaMessageInputStream.kt
> +    lateinit var cypressOtaResponseStream: Flow<CypressOtaResponse>
Wouldn't it make it immutable? :)

2025-01-06 08:59 UTC, luhmirin-s reviewed
Amazing work! I have few clarify questions about hot/cold flows, I think there is a potential to simplify it a bit further.

2025-01-06 08:59 UTC, luhmirin-s commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/main/packet/PacketRouter.kt
> +/**
Why did you move the doc comment before the imports?

2025-01-06 08:59 UTC, luhmirin-s commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/main/packet/PacketRouter.kt
> +                    packetRoute?.emit(packet)
Could be simplified to just 
```
routeIdMap[routeDesignator]?.let { internalPacketRoutes[it] }?.emit(packet)
```

2025-01-06 08:59 UTC, luhmirin-s commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/cypressota/CypressOtaMessageInputStream.kt
>      }
Considering that the response receiver now runs on noncancellable context, how sure are you that this way of disposing of flows does not leak anything? 

I feel that the response stream should be a hot flow that is started/stopped in connect/disconnect, but I cannot fully back that up at the moment.

2025-01-06 08:59 UTC, luhmirin-s commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapperV2.kt
> +    private val activeTriggerListeners = Collections.synchronizedSet(mutableSetOf<ScannerTriggerListener>())
Would making `triggerButtonFlow` into a hot flow (e.g. SharedFlow) help to simplify this observer business? Every "observer" would be able to collect the trigger events directly.

2025-01-06 08:59 UTC, luhmirin-s commented on gradle/libs.versions.toml
> -#RxJava2
🎉

2025-01-08 10:44 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/main/MainMessageInputStream.kt
> +    lateinit var un20Responses: Flow<Un20Response>
Using lateinit for the Flow properties in this class is appropriate because these properties are expected to be initialized later, specifically in the connect method. I wanted to  ensure that the properties are not null and are only initialized when the connect method is called.  If I use emptyFlow() instead, the properties would be initialized with an empty flow, which might not be the intended behavior. I want the callers  to this class to get an exception if they they tried to access the flows before connecting

2025-01-08 10:55 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/cypressota/CypressOtaMessageInputStream.kt
>      }
I believe setting `cypressOtaResponseStream = emptyFlow()` is unnecessary, as disconnecting this stream should prevent any caller from using the `CypressOtaMessageInputStream` class. If they attempt to use it, an `IncorrectModeException` would be thrown.

I will remove this  line

2025-01-08 10:57 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/channel/MainMessageChannel.kt
> +    @NonCancellableIO coroutineContext: CoroutineContext,
yes it is necessary  as NonCancellableIO  resolves the inconsistency issue where canceling a fingerprint capture and immediately starting another caused the scanner to enter a problematic state especially in the NEC flow .

2025-01-08 10:58 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/main/packet/PacketRouter.kt
> +/**
it was done by chatgpt :D

2025-01-08 10:59 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/main/packet/PacketRouter.kt
> +                    packetRoute?.emit(packet)
Done

2025-01-08 11:02 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/wrapper/ScannerWrapperV2.kt
> +    private val activeTriggerListeners = Collections.synchronizedSet(mutableSetOf<ScannerTriggerListener>())
I intended to completely remove the `registerTriggerListener` and `unregisterTriggerListener` methods and instead expose a `SharedFlow` to the callers. However, I'm constrained by the old implementation of `ScannerWrapperV1`, which interacts with legacy Java code. To avoid breaking any V1 functionality, I chose not to modify it.

2025-01-08 12:42 UTC, BurningAXE approved these changes
Phenomenal!
Tested it with Vero E1s and E3s and didn't find any issues! OTAs seem to be working this time.
Minor remarks about some lateinits that can probably be avoided.

2025-01-08 12:42 UTC, BurningAXE commented on gradle/libs.versions.toml
> -#RxJava2
🎉

2025-01-08 14:44 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v2/incoming/cypressota/CypressOtaMessageInputStream.kt
> +    lateinit var cypressOtaResponseStream: Flow<CypressOtaResponse>
I prefer `lateinit` here because it enforces explicit initialization and throws an error if accessed before being set. This ensures `connect` is always called before use, avoiding subtle bugs that could arise from accidentally processing an `emptyFlow()`.

2025-01-08 19:54 UTC, alexandr-simprints approved these changes

2025-01-09 03:53 UTC, meladRaouf commented on fingerprint/infra/scanner/src/main/java/com/simprints/fingerprint/infra/scanner/v1/ScannerUtils.kt
> -
It's really strange that this code is entirely unused. I went through the Git history and couldn't find any instance of it being used.

2025-01-09 07:57 UTC, luhmirin-s approved these changes

2025-01-13 08:56 UTC, merged