fix  getUserId issue
Simprints/Android-Simprints-ID pull request #543
Opened 2024-02-01 10:04 UTC by meladRaouf

2024-02-01 10:11 UTC, alex-vt requested changes
The unit test probably should be ported too (replace `GROUP` with `Partitioning` there).

2024-02-01 10:27 UTC, alex-vt approved these changes

2024-02-01 10:43 UTC, alex-vt requested changes

2024-02-01 10:43 UTC, alex-vt commented on infra/event-sync/src/test/java/com/simprints/infra/eventsync/status/down/EventDownSyncScopeRepositoryTest.kt
For reference: https://github.com/Simprints/Android-Simprints-ID/pull/538/files#diff-5ef858eb5a58e8a3c5f41eba2263985fd80e986141fb2252b1767341a65fd6e1

2024-02-01 11:04 UTC, alex-vt approved these changes

2024-02-01 12:18 UTC, BurningAXE approved these changes

2024-02-05 09:20 UTC, alexandr-simprints approved these changes

2024-02-05 14:55 UTC, luhmirin-s commented
I think this is redundant since we added a fix for MS-201 into the next release.

2024-02-07 08:26 UTC, meladRaouf commented
This fix was already added to  2023.4.1

2024-02-07 08:26 UTC, closed without merging